export const ADD_TO_CART="ADD_TO_CART"
export const DELETE_CART="DELETE_CART"
export const UPDATE_CART="UPDATE_CART"

export const REQUEST_ORDERS="REQUEST_ORDERS";
export const REQUEST_ORDERS_SUCCESS="REQUEST_ORDERS_SUCCESS";
export const ADD_ORDERS_SUCCESS="ADD_ORDERS_SUCCESS";
export const REQUEST_ORDERS_FAILURE="REQUEST_ORDERS_FAILURE";
