export const REQUEST_USER_SIGNUP="REQUEST_USER_SIGNUP"
export const REQUEST_USER_SIGNUP_SUCCESS="REQUEST_USER_SIGNUP_SUCCESS"
export const REQUEST_USER_SIGNUP_FAILURE="REQUEST_USER_SIGNUP_FAILURE"

export const REQUEST_USER_LOGIN="REQUEST_USER_LOGIN"
export const REQUEST_USER_LOGIN_SUCCESS="REQUEST_USER_LOGIN_SUCCESS"
export const REQUEST_USER_LOGIN_FAILURE="REQUEST_USER_LOGIN_FAILURE"
export const FETCH_USER_PROFILE="FETCH_USER_PROFILE";
export const FETCH_USER_PROFILE_FAILURE="FETCH_USER_PROFILE_FAILURE";
export const USER_LOGOUT="USER_LOGOUT";
