export const REQUEST_BARS="REQUEST_BARS";
export const REQUEST_BARS_SUCCESS="REQUEST_BARS_SUCCESS";
export const REQUEST_BARS_FAILURE="REQUEST_BARS_FAILURE";

export const REQUEST_SINGLE_PRODUCT="REQUEST_SINGLE_PRODUCT";